load("@io_bazel_rules_go//go:def.bzl", "go_library")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "utils",
    srcs = ["net.go"],
    importpath = "github.com/kombi/utils",
)
