licenses(["notice"])  # Apache 2.0

load("@io_bazel_rules_go//go:def.bzl", "go_library")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "test_utils",
    srcs = [
        "net.go",
        "emu.go",
    ],
    importpath = "github.com/waterfall/test_utils",
)
